// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterNotebooks) DeepCopyInto(out *JupyterNotebooks) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterNotebooks.
func (in *JupyterNotebooks) DeepCopy() *JupyterNotebooks {
	if in == nil {
		return nil
	}
	out := new(JupyterNotebooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JupyterNotebooks) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterNotebooksList) DeepCopyInto(out *JupyterNotebooksList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JupyterNotebooks, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterNotebooksList.
func (in *JupyterNotebooksList) DeepCopy() *JupyterNotebooksList {
	if in == nil {
		return nil
	}
	out := new(JupyterNotebooksList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JupyterNotebooksList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterNotebooksSpec) DeepCopyInto(out *JupyterNotebooksSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterNotebooksSpec.
func (in *JupyterNotebooksSpec) DeepCopy() *JupyterNotebooksSpec {
	if in == nil {
		return nil
	}
	out := new(JupyterNotebooksSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterNotebooksStatus) DeepCopyInto(out *JupyterNotebooksStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterNotebooksStatus.
func (in *JupyterNotebooksStatus) DeepCopy() *JupyterNotebooksStatus {
	if in == nil {
		return nil
	}
	out := new(JupyterNotebooksStatus)
	in.DeepCopyInto(out)
	return out
}
