apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebooks-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jupyter-notebooks-operator
  template:
    metadata:
      labels:
        name: jupyter-notebooks-operator
    spec:
      serviceAccountName: jupyter-notebooks-operator
      containers:
        - name: jupyter-notebooks-operator
          # Replace this with the built image name
          image: quay.io/aaziz/jupyter-notebooks-operator:v0.0.1
          command:
          - jupyter-notebooks-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "jupyter-notebooks-operator"
